apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: appscode-charts-oci
  namespace: default
spec:
  interval: 30m
  provider: generic
  timeout: 1m
  type: oci
  url: oci://ghcr.io/appscode-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openfga
  namespace: default
spec:
  interval: 60m
  releaseName: openfga
  targetNamespace: default
  storageNamespace: default
  install:
    createNamespace: true
  chart:
    spec:
      chart: openfga
      version: "0.2.6"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: default
