apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  aceinternal.override: |
    file /etc/coredns/custom/db.ace.internal ace.internal
  db.ace.internal: |
    $ORIGIN ace.internal.
    @ 3600 IN SOA sns.dns.icann.org. noc.dns.icann.org. 2017042745 7200 3600 1209600 3600
      3600 IN NS a.iana-servers.net.
      3600 IN NS b.iana-servers.net.
           IN A 139.144.198.96
