apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  example.server: |
    example.org {
      log
      whoami
    }
  ace.internal.server: |
    ;; A Records
    ace.internal. 1 IN  A 139.144.198.96
  ace.internal.override: |
    file /etc/coredns/custom/ace.internal.server ace.internal



