apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  # example.server: |
  #   ace.internal {
  #     log
  #     whoami
  #   }
  aceinternal.server: |
    ; ace.internal test file
    ace.internal.            IN      SOA     sns.dns.icann.org. noc.dns.icann.org. 2015082541 7200 3600 1209600 3600
    ace.internal.            IN      NS      b.iana-servers.net.
    ace.internal.            IN      NS      a.iana-servers.net.
    ;; A Records
    ace.internal. 1 IN  A 139.144.198.96
  aceinternal.override: |
    file /etc/coredns/custom/aceinternal.server ace.internal
