apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  aceinternal.override: |
    file /etc/coredns/custom/db.aceinternal.server ace.internal
  db.aceinternal.server: |
    @ 3600 IN SOA sns.dns.icann.org. noc.dns.icann.org. 2017042745 7200 3600 1209600 3600
      3600 IN NS a.iana-servers.net.
      3600 IN NS b.iana-servers.net.

    www     IN A     139.144.198.96
  # example.server: |
  #   ace.internal {
  #   }


  #   example.org {
  #     log
  #     whoami
  #     file db.example.org
  #     transfer {
  #       to * 10.240.1.1
  #     }
  #   }

  # db.example.org: |
  #   $ORIGIN example.org.
  #   @ 3600 IN SOA sns.dns.icann.org. noc.dns.icann.org. 2017042745 7200 3600 1209600 3600
  #     3600 IN NS a.iana-servers.net.
  #     3600 IN NS b.iana-servers.net.

  #   www     IN A     127.0.0.1
