apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  aceinternal.override: |
    file /etc/coredns/custom/db.aceinternal.server ace.internal
  db.aceinternal.server: |
    ;; A Records
    ace.internal. 1 IN  A 139.144.198.96
