# sample:
# - https://github.com/kubernetes/apiserver/blob/230bc6c645825161e07cc4dc79b8055b84d4f516/pkg/apis/audit/types.go#L145
# - https://raw.githubusercontent.com/kubernetes/website/master/docs/tasks/debug-application-cluster/audit-policy.yaml
# - https://github.com/kubernetes/kubernetes/blob/411881803f20a6c7390588dc194945c2d575e5df/cluster/gce/gci/configure-helper.sh#L703
apiVersion: audit.k8s.io/v1beta1
kind: Policy
# Don't generate audit events for all requests in RequestReceived stage.
omitStages:
  - RequestReceived
rules:
- level: Metadata
  # users: ["system:kube-proxy"]
  resources:
  - group: "" # core
  - group: "admissionregistration.k8s.io"
  - group: "apiextensions.k8s.io"
  - group: "apiregistration.k8s.io"
  - group: "apps"
  - group: "authentication.k8s.io"
  - group: "authorization.k8s.io"
  - group: "autoscaling"
  - group: "batch"
  - group: "certificates.k8s.io"
  - group: "extensions"
  - group: "metrics.k8s.io"
  - group: "networking.k8s.io"
  - group: "policy"
  - group: "rbac.authorization.k8s.io"
  - group: "settings.k8s.io"
  - group: "storage.k8s.io"
