apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 60m
  url: https://charts.bitnami.com/bitnami

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: cert-manager
      version: '1.3.21'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  releaseName: cert-manager
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  values:
    installCRDs: true
